[versions]
agp = "8.7.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
activityCompose = "1.9.2"
#compose = "1.7.0-alpha07"
compose = "1.7.0-alpha08"
#"1.6.8" - good
#"1.7.0-alpha01" - good
#"1.7.0-alpha05" - good
#"1.7.0-alpha06" - good
#"1.7.0-alpha07" - good
#"1.7.0-alpha08" - bad
material3 = "1.2.1"
#composeBom = "2024.08.00"
composeBom = "2024.09.00"
#"2024.04.01" - good
#"2024.06.00" - good
#"2024.08.00" - good
#"2024.09.00" - bad
#"2024.09.03" - bad

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
#androidx-ui = { group = "androidx.compose.ui", name = "ui" }
#androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
#androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
#androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
#androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
#androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
